grails-app/domain/com/linksharing/resources/DocumentResource.groovy
package com.linksharing.resources

import com.linksharing.Subscription
import com.linksharing.Topic
import com.linksharing.User
import com.linksharing.resources.Resource

class DocumentResource extends Resource {

    String filepath
    Date dateCreated
    Date lastUpdated



    static DOCUMENT_CONTENT_TYPE="application/pdf"
    static transients = ['contenttype','fileName']
    static constraints = {

        /*contenttype validator: {

            this.contenttype=="application/pdf"?true:'contenttype.not.contain.pdf'
        }*/

    }



    String getFileName()
    {
        String[] split=this.filepath.split('/')
        return split[split.length-1]

    }

    def afterInsert= {

        log.info "insert after"
        withNewSession {

            Topic topic=this.topic
            List<Subscription> subscriptions=Subscription.findAllByTopic(topic)
            subscriptions.each {

                ReadingItem readingItem=new ReadingItem(isRead: false ,user: it.user,resource: this)
                readingItem.save(flush: true,failOnError: true)







            }


        }

    }

    }

grails-app/controllers/com/linksharing/resources/DocumentResourceController.groovy
package com.linksharing.resources

import com.linksharing.Constants
import com.linksharing.Topic

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional


class DocumentResourceController {


    @Transactional
    def upload() {
        def file = params.document
        if (file.empty) {
            flash.message = "File cannot be empty"
        } else {
            Random random = new Random()
            Integer num = random.nextInt()
            def documentInstance = new DocumentResource()
            def filenames = num + file.originalFilename
            documentInstance.filepath = grailsApplication.config.linksharing.documents.folderPath + filenames
            documentInstance.createdBy = session.user
            Long id = Long.valueOf(params.topic).longValue();
            Topic topicn = Topic.findById(id)
            documentInstance.topic = topicn
            documentInstance.description = params.description
            file.transferTo(new File(grailsApplication.config.linksharing.documents.folderPath + filenames))
            if (documentInstance.save(flush: true, failOnError: true)) {
                flash.message = "document stored successfully"
            }
            else {
                flash.message = "document cannot stored successfully"
            }
        }

        redirect(controller: 'user', action: 'index')

    }


    def download(Long id) {
        println "under download"
        DocumentResource documentResource = DocumentResource.get(id)
        println("${documentResource}")
        if (documentResource == null) {
            println "not found file"
            flash.message = "Document not found."
            redirect(controller: 'user', action: 'index')

        } else {
            response.setContentType("${Constants.DOCUMENT_CONTENT_TYPE}")
            response.setHeader("Content-Disposition", "Attachment;Filename=\"${documentResource.fileName}\"")
            def file = new File(documentResource.filepath)
            def fileInputStream = new FileInputStream(file)
            def outputStream = response.getOutputStream()
            byte[] buffer = new byte[4096];
            int len;
            while ((len = fileInputStream.read(buffer)) > 0) {
                outputStream.write(buffer, 0, len);
            }
            outputStream.flush()
            outputStream.close()
            fileInputStream.close()
        }
    }


}

grails-app/controllers/com/linksharing/resources/ReadingItemController.groovy
package com.linksharing.resources

import com.linksharing.User
import grails.converters.JSON


class ReadingItemController {

    def checkReads(boolean isRead,Long resourceid) {

        User user=session.user
        Resource resource=Resource.get(resourceid)
        ReadingItem.executeUpdate("update ReadingItem set isRead=true where resource=? and user=?",[resource,user])
        forward(controller: "user",action: "index",params: ['user':user,'resource':resource])
        flash.message="message is read"
        render([0:"message save sucessfully",1:"errror while updating is read"] as JSON)

    }

}

grails-app/views/documentResource/_create.gsp
<%@ page import="com.linksharing.Topic" %>

<div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>

                <h4 class="modal-title"><span>Share Document(popup)</span></h4>

            </div>
            <div class="modal-body" >
                <g:uploadForm  controller="documentResource" action="upload">

                    <label for="document" class="col-xs-3">Document*:</label>
                    <input type='file'  id="document" name='document'/>
                    <br>
                    <br>
                    <label for="description" class="col-xs-3">Description:</label>
                    <g:textArea name="description"  rows="5" cols="40"></g:textArea>
                    <br>
                    <br>
                    <label for="topic" class="col-xs-3">Topics:</label>

                    <div class="dropdown col-xs-7 " style="width:400px">

                        <g:select name="topic" from="${Topic.list()}" optionValue="name" value="it" optionKey="id" ></g:select>

                        %{--<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Topics--}%
                        %{--<span class="caret"></span></button>--}%
                        %{--<ul class="dropdown-menu">--}%
                        %{--</ul>--}%
                    </div>
                    <br>
                    <br>
                    <div>
                        <g:actionSubmit value="Save" controller="documentResource" action="upload"/>
                        <g:actionSubmit value="Cancel" controller="user" action="index"/>
                    </div>

                </g:uploadForm>
            </div>
        </div>
    </div>

grails-app/views/documentResource/_form.gsp
<%@ page import="com.linksharing.resources.DocumentResource" %>



<div class="fieldcontain ${hasErrors(bean: documentResourceInstance, field: 'description', 'error')} required">
	<label for="description">
		<g:message code="documentResource.description.label" default="Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="description" required="" value="${documentResourceInstance?.description}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: documentResourceInstance, field: 'createdBy', 'error')} required">
	<label for="createdBy">
		<g:message code="documentResource.createdBy.label" default="Created By" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="createdBy" name="createdBy.id" from="${com.linksharing.User.list()}" optionKey="id" required="" value="${documentResourceInstance?.createdBy?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: documentResourceInstance, field: 'filepath', 'error')} required">
	<label for="filepath">
		<g:message code="documentResource.filepath.label" default="Filepath" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="filepath" required="" value="${documentResourceInstance?.filepath}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: documentResourceInstance, field: 'readingItems', 'error')} ">
	<label for="readingItems">
		<g:message code="documentResource.readingItems.label" default="Reading Items" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${documentResourceInstance?.readingItems?}" var="r">
    <li><g:link controller="readingItem" action="show" id="${r.id}">${r?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="readingItem" action="create" params="['documentResource.id': documentResourceInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'readingItem.label', default: 'ReadingItem')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: documentResourceInstance, field: 'resourceRating', 'error')} ">
	<label for="resourceRating">
		<g:message code="documentResource.resourceRating.label" default="Resource Rating" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${documentResourceInstance?.resourceRating?}" var="r">
    <li><g:link controller="resourceRating" action="show" id="${r.id}">${r?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="resourceRating" action="create" params="['documentResource.id': documentResourceInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'resourceRating.label', default: 'ResourceRating')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: documentResourceInstance, field: 'topic', 'error')} required">
	<label for="topic">
		<g:message code="documentResource.topic.label" default="Topic" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="topic" name="topic.id" from="${com.linksharing.Topic.list()}" optionKey="id" required="" value="${documentResourceInstance?.topic?.id}" class="many-to-one"/>

</div>

grails-app/views/documentResource/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'documentResource.label', default: 'DocumentResource')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-documentResource" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-documentResource" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${documentResourceInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${documentResourceInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:documentResourceInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/documentResource/edit.gsp
<%@ page import="com.linksharing.resources.DocumentResource" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'documentResource.label', default: 'DocumentResource')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-documentResource" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-documentResource" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${documentResourceInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${documentResourceInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:documentResourceInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${documentResourceInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/documentResource/index.gsp
<%@ page import="com.linksharing.resources.DocumentResource" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'documentResource.label', default: 'DocumentResource')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-documentResource" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-documentResource" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="description" title="${message(code: 'documentResource.description.label', default: 'Description')}" />
					
						<th><g:message code="documentResource.createdBy.label" default="Created By" /></th>
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'documentResource.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="filepath" title="${message(code: 'documentResource.filepath.label', default: 'Filepath')}" />
					
						<g:sortableColumn property="lastUpdated" title="${message(code: 'documentResource.lastUpdated.label', default: 'Last Updated')}" />
					
						<th><g:message code="documentResource.topic.label" default="Topic" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${documentResourceInstanceList}" status="i" var="documentResourceInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${documentResourceInstance.id}">${fieldValue(bean: documentResourceInstance, field: "description")}</g:link></td>
					
						<td>${fieldValue(bean: documentResourceInstance, field: "createdBy")}</td>
					
						<td><g:formatDate date="${documentResourceInstance.dateCreated}" /></td>
					
						<td>${fieldValue(bean: documentResourceInstance, field: "filepath")}</td>
					
						<td><g:formatDate date="${documentResourceInstance.lastUpdated}" /></td>
					
						<td>${fieldValue(bean: documentResourceInstance, field: "topic")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${documentResourceInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/documentResource/show.gsp
<%@ page import="com.linksharing.resources.DocumentResource" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'documentResource.label', default: 'DocumentResource')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-documentResource" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-documentResource" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list documentResource">
			
				<g:if test="${documentResourceInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="documentResource.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${documentResourceInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${documentResourceInstance?.createdBy}">
				<li class="fieldcontain">
					<span id="createdBy-label" class="property-label"><g:message code="documentResource.createdBy.label" default="Created By" /></span>
					
						<span class="property-value" aria-labelledby="createdBy-label"><g:link controller="user" action="show" id="${documentResourceInstance?.createdBy?.id}">${documentResourceInstance?.createdBy?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${documentResourceInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="documentResource.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${documentResourceInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${documentResourceInstance?.filepath}">
				<li class="fieldcontain">
					<span id="filepath-label" class="property-label"><g:message code="documentResource.filepath.label" default="Filepath" /></span>
					
						<span class="property-value" aria-labelledby="filepath-label"><g:fieldValue bean="${documentResourceInstance}" field="filepath"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${documentResourceInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="documentResource.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${documentResourceInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${documentResourceInstance?.readingItems}">
				<li class="fieldcontain">
					<span id="readingItems-label" class="property-label"><g:message code="documentResource.readingItems.label" default="Reading Items" /></span>
					
						<g:each in="${documentResourceInstance.readingItems}" var="r">
						<span class="property-value" aria-labelledby="readingItems-label"><g:link controller="readingItem" action="show" id="${r.id}">${r?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${documentResourceInstance?.resourceRating}">
				<li class="fieldcontain">
					<span id="resourceRating-label" class="property-label"><g:message code="documentResource.resourceRating.label" default="Resource Rating" /></span>
					
						<g:each in="${documentResourceInstance.resourceRating}" var="r">
						<span class="property-value" aria-labelledby="resourceRating-label"><g:link controller="resourceRating" action="show" id="${r.id}">${r?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${documentResourceInstance?.topic}">
				<li class="fieldcontain">
					<span id="topic-label" class="property-label"><g:message code="documentResource.topic.label" default="Topic" /></span>
					
						<span class="property-value" aria-labelledby="topic-label"><g:link controller="topic" action="show" id="${documentResourceInstance?.topic?.id}">${documentResourceInstance?.topic?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:documentResourceInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${documentResourceInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>