grails-app/domain/com/linksharing/resources/ResourceRating.groovy
package com.linksharing.resources

import com.linksharing.User
import com.linksharing.resources.Resource

class ResourceRating {
//    Resource resource
    Integer score
    User user
    Date dateCreated
    Date lastUpdated

    static belongsTo = [resource:Resource]

    static constraints = {

        score  min: 1,max: 5
        user unique: ['resource']
    }
}

grails-app/controllers/com/linksharing/resources/ResourceRatingController.groovy
package com.linksharing.resources

import com.linksharing.User

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional


class ResourceRatingController {

    def resourceRatingSave( Long resourceid, int score) {

        println "under resource controller+${resourceid}+${score}"
        User user=session.user
        Resource resource=Resource.get(resourceid)
        println "check resource+${resource}"
        println "check user+${user}"
        ResourceRating resourceRating1=ResourceRating.findByResourceAndUser(resource,user)
        if(resourceRating1)
        {
           ResourceRating.executeUpdate("update ResourceRating set score=? where resource=? and user=?",[score,resource,user])
            render "success"
            println "under update"
        }
        else {
            ResourceRating resourceRating = new ResourceRating(score: score, user: user)
            resource.addToResourceRating(resourceRating)
            if(resource.save(flush: true,failOnError: true))
            {

                render "success"
            }

        }
        redirect(controller: 'resource', action: 'showresource',params: [id:resourceid])



    }
}

grails-app/views/resourceRating/_form.gsp
<%@ page import="com.linksharing.resources.ResourceRating" %>



<div class="fieldcontain ${hasErrors(bean: resourceRatingInstance, field: 'score', 'error')} required">
	<label for="score">
		<g:message code="resourceRating.score.label" default="Score" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="score" type="number" min="1" max="5" value="${resourceRatingInstance.score}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: resourceRatingInstance, field: 'user', 'error')} required">
	<label for="user">
		<g:message code="resourceRating.user.label" default="User" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="user" name="user.id" from="${com.linksharing.User.list()}" optionKey="id" required="" value="${resourceRatingInstance?.user?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: resourceRatingInstance, field: 'resource', 'error')} required">
	<label for="resource">
		<g:message code="resourceRating.resource.label" default="Resource" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="resource" name="resource.id" from="${com.linksharing.resources.Resource.list()}" optionKey="id" required="" value="${resourceRatingInstance?.resource?.id}" class="many-to-one"/>

</div>

grails-app/views/resourceRating/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'resourceRating.label', default: 'ResourceRating')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-resourceRating" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-resourceRating" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${resourceRatingInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${resourceRatingInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:resourceRatingInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/resourceRating/edit.gsp
<%@ page import="com.linksharing.resources.ResourceRating" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'resourceRating.label', default: 'ResourceRating')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-resourceRating" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-resourceRating" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${resourceRatingInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${resourceRatingInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:resourceRatingInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${resourceRatingInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/resourceRating/index.gsp
<%@ page import="com.linksharing.resources.ResourceRating" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'resourceRating.label', default: 'ResourceRating')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-resourceRating" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-resourceRating" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="score" title="${message(code: 'resourceRating.score.label', default: 'Score')}" />
					
						<th><g:message code="resourceRating.user.label" default="User" /></th>
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'resourceRating.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="lastUpdated" title="${message(code: 'resourceRating.lastUpdated.label', default: 'Last Updated')}" />
					
						<th><g:message code="resourceRating.resource.label" default="Resource" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${resourceRatingInstanceList}" status="i" var="resourceRatingInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${resourceRatingInstance.id}">${fieldValue(bean: resourceRatingInstance, field: "score")}</g:link></td>
					
						<td>${fieldValue(bean: resourceRatingInstance, field: "user")}</td>
					
						<td><g:formatDate date="${resourceRatingInstance.dateCreated}" /></td>
					
						<td><g:formatDate date="${resourceRatingInstance.lastUpdated}" /></td>
					
						<td>${fieldValue(bean: resourceRatingInstance, field: "resource")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${resourceRatingInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/resourceRating/show.gsp
<%@ page import="com.linksharing.resources.ResourceRating" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'resourceRating.label', default: 'ResourceRating')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-resourceRating" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-resourceRating" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list resourceRating">
			
				<g:if test="${resourceRatingInstance?.score}">
				<li class="fieldcontain">
					<span id="score-label" class="property-label"><g:message code="resourceRating.score.label" default="Score" /></span>
					
						<span class="property-value" aria-labelledby="score-label"><g:fieldValue bean="${resourceRatingInstance}" field="score"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${resourceRatingInstance?.user}">
				<li class="fieldcontain">
					<span id="user-label" class="property-label"><g:message code="resourceRating.user.label" default="User" /></span>
					
						<span class="property-value" aria-labelledby="user-label"><g:link controller="user" action="show" id="${resourceRatingInstance?.user?.id}">${resourceRatingInstance?.user?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${resourceRatingInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="resourceRating.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${resourceRatingInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${resourceRatingInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="resourceRating.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${resourceRatingInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${resourceRatingInstance?.resource}">
				<li class="fieldcontain">
					<span id="resource-label" class="property-label"><g:message code="resourceRating.resource.label" default="Resource" /></span>
					
						<span class="property-value" aria-labelledby="resource-label"><g:link controller="resource" action="show" id="${resourceRatingInstance?.resource?.id}">${resourceRatingInstance?.resource?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:resourceRatingInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${resourceRatingInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>