grails-app/domain/com/linksharing/Subscription.groovy
package com.linksharing

class Subscription {
    Seriousness seriousness
    User user
    Topic topic
    Date dateCreated
    Date lastUpdated
    static belongsTo = [topic: Topic]

    static constraints = {
        seriousness nullable: false
        user nullable: false
        topic nullable: false, unique: ['user']
    }
}

grails-app/controllers/com/linksharing/SubscriptionController.groovy
package com.linksharing

import com.linksharing.resources.Resource

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional


class SubscriptionController {

    def userService

    static allowedMethods = [save: "GET", update: "PUT" ]


    def index() {
        List<Subscription> subscriptionList=Subscription.createCriteria().list(max:5){
        }
        def count=Subscription.count()
        render(view: "/subscription/subscriptionlist", model: ['subscriptionList':subscriptionList,'count':count])

    }

    def paginatesubscription()
    {
        List<Subscription> subscriptionList=Subscription.createCriteria().list (max:params.max,offset:params.offset){
        }
        def count=Subscription.count()
        render(view: "/subscription/subscriptionlist", model: ['subscriptionList':subscriptionList,'count':count])
    }

    def delete(Long id) {
        println "under delete subscription*******************${id}"
        Subscription subscription = Subscription.findById(id)
        if (subscription) {
            subscription.delete(flush:true)
            flash.message="unsubscribed"

        }
        render "success"

    }


    def save(Long id) {
        println "under save subscription"
        Topic topic = Topic.findById(id)
        Subscription subscription = new Subscription(seriousness: Seriousness.CASUAL, topic: topic, user: session.user)
        println("subscription is there +++++++++${subscription}++++++${topic} +++${session.user}")
        if (!subscription.validate()) {
            subscription.errors.each {
                println it
            }

        }
        else {
            Subscription.withNewTransaction {
                subscription.save(flush:true)
                flash.message="subscribed user"
            }


        }
    render "success"
    }


    def updateTo() {
        long  id=Long.parseLong(params.id)
        Seriousness seriousness=Seriousness.valueOF(params.seriousness)
        Subscription subscription = Subscription.findById(id)
        if ( subscription){
            subscription.seriousness=seriousness
            subscription.save(flush:true)
        }
        render "sucesss"





    }



}

grails-app/views/subscription/_form.gsp
<%@ page import="com.linksharing.Subscription" %>



<div class="fieldcontain ${hasErrors(bean: subscriptionInstance, field: 'seriousness', 'error')} required">
	<label for="seriousness">
		<g:message code="subscription.seriousness.label" default="Seriousness" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="seriousness" from="${com.linksharing.Seriousness?.values()}" keys="${com.linksharing.Seriousness.values()*.name()}" required="" value="${subscriptionInstance?.seriousness?.name()}" />

</div>

<div class="fieldcontain ${hasErrors(bean: subscriptionInstance, field: 'user', 'error')} required">
	<label for="user">
		<g:message code="subscription.user.label" default="User" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="user" name="user.id" from="${com.linksharing.User.list()}" optionKey="id" required="" value="${subscriptionInstance?.user?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: subscriptionInstance, field: 'topic', 'error')} required">
	<label for="topic">
		<g:message code="subscription.topic.label" default="Topic" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="topic" name="topic.id" from="${com.linksharing.Topic.list()}" optionKey="id" required="" value="${subscriptionInstance?.topic?.id}" class="many-to-one"/>

</div>

grails-app/views/subscription/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subscription.label', default: 'Subscription')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-subscription" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-subscription" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${subscriptionInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${subscriptionInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:subscriptionInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/subscription/edit.gsp
<%@ page import="com.linksharing.Subscription" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subscription.label', default: 'Subscription')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-subscription" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-subscription" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${subscriptionInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${subscriptionInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:subscriptionInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${subscriptionInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/subscription/index.gsp
<%@ page import="com.linksharing.Subscription" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subscription.label', default: 'Subscription')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-subscription" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-subscription" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="seriousness" title="${message(code: 'subscription.seriousness.label', default: 'Seriousness')}" />
					
						<th><g:message code="subscription.user.label" default="User" /></th>
					
						<th><g:message code="subscription.topic.label" default="Topic" /></th>
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'subscription.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="lastUpdated" title="${message(code: 'subscription.lastUpdated.label', default: 'Last Updated')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${subscriptionInstanceList}" status="i" var="subscriptionInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${subscriptionInstance.id}">${fieldValue(bean: subscriptionInstance, field: "seriousness")}</g:link></td>
					
						<td>${fieldValue(bean: subscriptionInstance, field: "user")}</td>
					
						<td>${fieldValue(bean: subscriptionInstance, field: "topic")}</td>
					
						<td><g:formatDate date="${subscriptionInstance.dateCreated}" /></td>
					
						<td><g:formatDate date="${subscriptionInstance.lastUpdated}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${subscriptionInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/subscription/show.gsp
<%@ page import="com.linksharing.Subscription" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subscription.label', default: 'Subscription')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-subscription" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-subscription" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list subscription">
			
				<g:if test="${subscriptionInstance?.seriousness}">
				<li class="fieldcontain">
					<span id="seriousness-label" class="property-label"><g:message code="subscription.seriousness.label" default="Seriousness" /></span>
					
						<span class="property-value" aria-labelledby="seriousness-label"><g:fieldValue bean="${subscriptionInstance}" field="seriousness"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${subscriptionInstance?.user}">
				<li class="fieldcontain">
					<span id="user-label" class="property-label"><g:message code="subscription.user.label" default="User" /></span>
					
						<span class="property-value" aria-labelledby="user-label"><g:link controller="user" action="show" id="${subscriptionInstance?.user?.id}">${subscriptionInstance?.user?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${subscriptionInstance?.topic}">
				<li class="fieldcontain">
					<span id="topic-label" class="property-label"><g:message code="subscription.topic.label" default="Topic" /></span>
					
						<span class="property-value" aria-labelledby="topic-label"><g:link controller="topic" action="show" id="${subscriptionInstance?.topic?.id}">${subscriptionInstance?.topic?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${subscriptionInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="subscription.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${subscriptionInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${subscriptionInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="subscription.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${subscriptionInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:subscriptionInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${subscriptionInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/subscription/subscriptionlist.gsp
<%@ page import="com.linksharing.*" %>


<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>

    <meta name="layout" content="main">
</head>

<body>
<div class="panel panel-default " style="border:1px solid black ">
    <div class=" panel panel-heading" style=" border:1px solid black;">
        <div class="row"><span class="col-xs-2">Subscriptions of topic</span>


    </div>
        </div>
        <div class="panel panel-body" style="-webkit-box-shadow: none">
            <table border="2" style="width:100%">
            <tr>
                <td style="background: cadetblue; "><strong>Topic Name</strong></td>
                <td style="background: cadetblue; "><strong>Subscribed user</strong></td>

            </tr>

            <g:each in="${subscriptionList}" >



          <tr>
              <td>${it.topic.name}</td>
              <td>
              <table>
                  <g:each in="${it.topic.subscriptions.user}" var="a">

                      <tr><td>${a.userName}</td></tr>


                  </g:each>
              </table>
              </td>
          </tr>






    </g:each>


    </table>
            </div>
    <g:paginate total="${count}" controller="subscription" action="paginatesubscription" />



</div>

</body>
</html>